FROM eclipse-temurin:21-jre-alpine

RUN addgroup -S springgrp \ 
	&& adduser -S springusr -G springgrp

USER springusr

WORKDIR /app

COPY target/*.jar app.jar

EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "app.jar" ]